config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点情報
  resources :bases, except: [:show, :new]
  
  resources :users do
    collection { post :import }
    get 'import'
    member do
      get 'export'
      get 'search'
      get 'working_employee'
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_user_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/request_overtime'
      patch 'attendances/update_overtime'
      get 'attendances/receive_overtime'
      patch 'attendances/decision_overtime'
      get 'attendances/edit_log'
      get 'attendances/receive_change_attendance'
      patch 'attendances/update_change_attendance'
      patch 'applies/request_one_month'
      get 'applies/receive_one_month_request'
      patch 'applies/decision_one_month_request'
      
    end
    resources :attendances, only: :update
  end
end
  

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user, optional: true
  
  validates :one_month, presence:true
  
   # 1ヶ月の勤怠申請・承認のステータス
  enum one_month_request_status: { なし: 0, 申請中: 1, 承認: 2, 否認: 3 }, _prefix: true

end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :set_user
  before_action :logged_in_user
  before_action :correct_user
  before_action :set_one_month
  before_action :superior_user, only: [:receive_one_month_request, :decision_one_month_request]
  before_action :select_superiors
  
  NO_CHECK_ERROR_MSG = "変更にチェックがないものは更新できません。"
  INVALID_ERROR_MSG = "無効な入力があった為、更新をキャンセルしました。"

  def request_one_month
    ActiveRecord::Base.transaction do
      one_month_request_params.each do |id ,item|
        if params[:user][:applies][id][:one_month_boss].blank?
          flash[:danger] = "上長を選択してください。"
          redirect_to user_url(date: params[:date]) and return
        else
          one_month_request = Apply.find(id)
          one_month_request.update_attributes!(item)
          @superior = User.find(params[:user][:applies][id][:one_month_boss])
        end
      end
    end
    flash[:success] = "#{@superior.name}に1ヶ月分の勤怠申請をしました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = INVALID_ERROR_MSG
    redirect_to user_url(date: params[:date])
  end
  
  def receive_one_month_request
    @receive_one_month_requests = Apply.order(:one_month).where(one_month_boss: @user.id, one_month_request_status: "申請中").group_by(&:user_id)
  end
  
  def decision_one_month_request
    ActiveRecord::Base.transaction do
      decision_one_month_request_params.each do |id ,item|
        decision_one_month_request = Apply.find(id)
        if params[:user][:applies][id][:change] == "true"
          decision_one_month_request.update_attributes!(item)
        else
          flash[:danger] = NO_CHECK_ERROR_MSG
        end
      end
    end
    flash[:success] = "1ヶ月勤怠申請の決裁を更新しました。"
    redirect_to user_url(current_user, date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = INVALID_ERROR_MSG
    redirect_to user_url(date: params[:date])
  end
  
  private  
   # 1ヶ月分の勤怠申請時のストロングパラメータ
    def one_month_request_params
      params.require(:user).permit(applies: [:one_month_boss, :one_month_request_status, :id, :_destroy])[:applies]
    end
    
    # 1ヶ月分の勤怠承認・否認時のストロングパラメータ
    def decision_one_month_request_params
      params.require(:user).permit(applies: [:one_month_request_status, :id, :_destroy])[:applies]
    end
  
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/views/applies/_receive_one_month_request.html.erb
<% provide(:class_text, 'receive_one_month_request') %>
<% provide(:button_text, '変更を送信する') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: applies_decision_one_month_request_user_path, local: true, method: :patch) do |f| %>
        <% @receive_one_month_requests.each do |key, receive_one_month_request| %>
          <table class="table table-bordered request-modal">
                
            <thead>
              <tr>
                <% @member = User.find(key) %>
                <h1 class="modal-title"><%= @member.name %>からの1ヶ月分の勤怠申請</h1>
                <th>月</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
                    
            <tbody>
              <% receive_one_month_request.each do |day| %>
                <%= f.fields_for "applies[]", day do |apply| %>
                <tr>
                  <td><%= day.one_month.month %></td>
                  <td><%= apply.select :one_month_request_status, Apply.one_month_request_statuses.keys.to_a, {}, class: "form-control" %></td>
                  <td><%= apply.check_box :change, { class: "check_box" }, true, false %></td>
                  <td><%= link_to "確認",user_path(id: @member, date: day.one_month), class: "btn btn-primary btn-#{yield(:class_text)}" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
       <% end %>
          
      <table>
        <div class="footer-button">
          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
            <button type="button" class="btn btn-primary btn-<%= yield(:class_text) %>" data-dismiss="modal">
              戻る
            </button>
        </div>
      </table>
    <% end %>
  </div>
</div>

app/views/applies/receive_one_month_request.js.erb
$("#receive-one-month-request").html("<%= escape_javascript(render 'receive_one_month_request') %>");
$("#receive-one-month-request").modal("show");