config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点情報
  resources :bases, except: [:show, :new]
  
  resources :users do
    collection { post :import }
    get 'import'
    member do
      get 'export'
      get 'search'
      get 'working_employee'
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_user_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/request_overtime'
      patch 'attendances/update_overtime'
      get 'attendances/receive_overtime'
      patch 'attendances/decision_overtime'
      get 'attendances/edit_log'
      get 'attendances/receive_change_attendance'
      patch 'attendances/update_change_attendance'
      patch 'applies/request_one_month'
      get 'applies/receive_one_month_request'
      patch 'applies/decision_one_month_request'
      
    end
    resources :attendances, only: :update
  end
end
  

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :applies, dependent: :destroy
  accepts_nested_attributes_for :applies, allow_destroy: true
  
  # 「remember_token」という仮想の属性を作成
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..30 }
  validates :employee_number, presence: true, uniqueness: true, allow_nil: true
  validates :basic_time, presence: true
  validates :work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデーターベースに記憶
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返す
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了する
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
 # ユーザーのログイン情報を破棄
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # CSVファイルのimportメソッド
  def self.import(file)
    CSV.foreach(file.path, encoding: 'Shift_JIS:UTF-8', headers: true) do |row|
      # emailが見つかれば、レコードを呼び出し、見つからなければ新規作成
      user = find_by(id: row["email"]) || new
      # CSVファイルからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
    end
  end

  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["id", "name", "email", "affiliation", "employee_number", "uid", "password", "password_confirmation",
      "superior", "admin", "basic_time", "designated_work_start_time", "designated_work_end_time"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :update_user_info, :edit_basic_info, :update_basic_info, :export]
  before_action :logged_in_user, only: [:show, :index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :export]
  before_action :correct_user, only: [:edit, :update, :export]
  before_action :admin_user, only: [:index, :destroy, :update_user_info, :edit_basic_info, :update_basic_info, :working_employee]
  before_action :superior_or_correct_user, only: :show
  before_action :set_one_month, only: [:show, :export]
  before_action :not_admin_user, only: :show
  before_action :select_superiors, only: :show
  
  def index
    @users = User.paginate(page: params[:page], per_page: 20 )
    if params[:name].present?
      @users = @users.get_by_name params[:name]
    end
  end
  
  def show
    @worked_sum = @attendances.where.not(started_at: nil).count
    @overtime_requests = Attendance.where(overtime_boss: @user.id, overtime_request_status: "申請中")
    @one_month_requests = Apply.where(one_month_boss: @user.id, one_month_request_status: "申請中")
    @change_attendance_requests = Attendance.where(edit_attendance_boss: @user.id, edit_attendance_request_status: "申請中")
    @one_month_attendance = @one_month_attendance.find_by(one_month: @first_day)
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user # 保存成功後、ログインする
      flash[:success] = "新規作成に成功しました。"
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  # 各ユーザーからの更新
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      if current_user.admin?
        redirect_to root_url
      else
        redirect_to @user
      end
    else
      render :edit
    end
  end
  
   # 管理者によるユーザー情報更新
  def update_user_info
    if @user.update_attributes(user_info_params)
      flash[:success] = "#{@user.name}のデータを更新しました。"
      redirect_to users_url
    else
      flash[:danger] = "データの更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to users_url
    end
  end
  
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_basic_info
  end
  
  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "基本情報を更新しました。"
      redirect_to users_url
    else
      flash.now[:danger] = "基本情報の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      render :edit_basic_info
    end
  end
  
  # ユーザー検索
  def search
    if params[:name].present?
      @users = User.where('name LIKE ?', "%#{params[:name]}%").paginate(page: params[:page], per_page: 20 )
      flash.now[:success] = "#{@users.count}件ヒットしました。"
    else
      @users = User.paginate(page: params[:page], per_page: 20 )
      flash.now[:danger] = "該当ユーザーはいませんでした。"
    end
    render :index
  end
  
  # CSVインポート
  def import
    if params[:file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to users_url
    else
      User.import(params[:file])
      flash[:success] = "CSVファイルをインポートしました。"
      redirect_to users_url
    end
  end
  
  # CSVエクスポート
  def export
    @worked_sum = @attendances.where.not(started_at: nil).count
    respond_to do |format|
      format.csv do
        send_data render_to_string, filename: "#{@user.name}_勤務表_(#{@first_day.strftime('%Y年%-m月')}).csv", type: :csv
      end
    end
  end
  
  # 出勤中社員判定
  def working_employee
    Attendance.where.not(started_at: nil).each do |attendance|
      if (Date.current == attendance.worked_on) && attendance.finished_at.nil?
        @working_users = User.all.includes(:attendances)
      end
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation)
    end
    
    def user_info_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, 
        :password_confirmation, :basic_time, :designated_work_start_time, :designated_work_end_time)
    end
    
   def basic_info_params
      params.require(:user).permit(:department, :basic_time, :work_time)
   end
   
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返す
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/model_error_messages', model: f.object %>
      
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
      
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
      
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}"%>
  <%= f.text_field :affiliation, class: "form-control" %>
      
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
      
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
      
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_user.html.erb
<%= form_with(model: user, url: update_user_info_user_path(user), method: :patch, local: true) do |f| %>
  <%= render 'shared/object_error_messages', object: user %>
  
  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>
  
  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>
  
  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.number_field :employee_number, class: "form-control" %>
   
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>
    
  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>
  
  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  
  <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>
  
  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:titile, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, 'Edit basic') %>
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '編集') %>
<h1>基本情報の更新</h1>
<h2>※メンテナンス中</h2>

<!--
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
      <% render 'shared/model_error_messages', model: f.object %>
      
      <%= f.label :basic_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :basic_time, class: "form-control" %>

      <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
      <%= f.time_field :work_time, class: "form-control" %>

     <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
    <% end %>

  </div>
</div>
-->

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<% provide(:class_text, 'user--index') %>
<% provide(:button_text, '編集する') %>

<h1>ユーザー一覧</h1>

<div class="container">
  <div class="row form-group">
    <div class="col-md-4 col-md-offset-1" id="csv-group">
      <%= form_tag import_users_path, method: :post, multipart: true do %>
         <div class="search_item">
            <%= button_tag "ファイルを選択", class: %i(csv_input_btn), type: 'button', onclick: "$('#file_input').click();" %>
            <%= text_field_tag 'filename',"", id: "filename", disabled: true, class: "form-control" %>
            <%= file_field_tag :file, id: "file_input", style: "display: none;", onchange: "file_selected($(this));" %>
          </div>
            <%= submit_tag "CSVをインポート", class: "btn btn-primary form-control btn-csv" %>
        <% end %>
      <div>
    </div>
  </div>
  
  <script type="text/javascript">
    function file_selected(file_field){
      var filename = $(file_field)[0].files[0].name;
      $("#filename").val(filename);
    }
  </script>
    
    <div class="col-md-4 col-md-offset-2" id="search-users">
      <p>ユーザー名検索</p>
      <%= form_with url: search_user_path(@users), method: :get, local: true do |f|  %>
        <%= f.text_field :name, placeholder: "キーワードを入力..." %>
        <%= f.submit "検索", class: " btn-primary" %>
      <% end %>
    </div>
    
    <div class=" row col-md-10 col-md-offset-1">
      <%= will_paginate %>
      <p>
        <% @users.each do |user| %>
          <% if current_user.admin? && !current_user?(user) %>
            <%= user.name %><br>
            <p></p>
              <%= link_to "削除", user, method: :delete,
                  data: { confirm: "削除してもよろしいですか？" },
                  class: "btn btn-primary" %><br>
            <div class="panel-group">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h4 class="panel-title">
                    <div class="collaps">
                      <a href="#collapse-edit<%= user.id %>" data-toggle="collapse" class="btn btn-lg btn-primary">編集</a>
                    </div>
                  </h4>
                </div>
                <div id="collapse-edit<%= user.id %>" class="panel-collapse collapse">
                  <div class="panel-body"><%= render 'user', { user: user } %></div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </p>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "◀", user_path(date: @first_day.prev_month), class: "btn btn-primary" if current_user == @user %>&nbsp;&nbsp;
          <%= l(@first_day, format: :middle) %>時間管理表&nbsp;&nbsp;
          <%= link_to "▶", user_path(date: @first_day.next_month), class: "btn btn-primary" if current_user == @user %>
        </td>
      <td>
        指定勤務開始時間<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3">基本時間<%= format_basic_info(@user.basic_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>
    
    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>社員番号</td>
      <td><%= @user.employee_number %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>


<div class="request-display">
  <% if @user.superior && current_user == @user %>
    <p>【所属長承認申請のお知らせ】<%= link_to "通知が#{@one_month_requests.count}件あります。", applies_receive_one_month_request_user_path(@user), remote: true,
        class: "receive-request-link" if @one_month_requests.present? %>
    </p>
    <p>【勤怠変更申請のお知らせ】<%= link_to "通知が#{@change_attendance_requests.count}件あります。", attendances_receive_change_attendance_user_path(@user), remote: true,
        class: "receive-request-link" if @change_attendance_requests.present? %>
    </p>
    <p>【残業申請のお知らせ】<%= link_to "通知が#{@overtime_requests.count}件あります。", attendances_receive_overtime_user_path(@user), remote: true,
        class: "receive-request-link" if @overtime_requests.present? %>
    </p>
  <% end %>
</div>


<div class="btn-users-shows">
  <% if current_user == @user %>
    <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day),  class: "btn btn-primary" %>
    <%= link_to "CSV出力",export_user_path(date: @first_day, format: :csv), class: "btn btn-primary" %><br>
    <%= link_to "勤怠修正ログ（承認済）", attendances_edit_log_user_path, class: "btn btn-primary" %>
  <% end %>
</div>
  
<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">【所定外勤務】</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <% if current_user == @user %>
          <th>出退勤ボタン</th>
        <% else %>
          <th></th>
        <% end %>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>
      
    <tbody>
      <% @attendances.each do |day| %>
        <%
          day_of_week_color = case $days_of_the_week[day.worked_on.wday]
          when "土"
            "text-primary"
          when "日"
            "text-danger"
          end
        %>
        <tr>
          <td><%= link_to "残業申請", attendances_request_overtime_user_path(date: day.worked_on), remote: true, class: "btn btn-default btn-primary" if current_user == @user %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= day_of_week_color %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <% if day.after_started_at.nil? || day.edit_attendance_request_status == "否認" %>
            <td><%= day.started_at.hour if day.started_at.present? %></td>
            <td><%= set_minutes(day.started_at) if day.started_at.present? %></td>
          <% else %>
            <td><%= day.after_started_at.hour %></td>
            <td><%= set_minutes(day.after_started_at) %></td>
          <% end %>
          <% if current_user == @user %>
            <td>
              <% if btn_text = attendance_state(day) %>
                <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-block btn-primary btn-attendance" %>
              <% end %>
            </td>
          <% else %>
            <td></td>
          <% end %>
          <% if day.after_finished_at.nil? || day.edit_attendance_request_status == "否認" %>
            <td><%= day.finished_at.hour if day.finished_at.present? %></td>
            <td><%= set_minutes(day.finished_at) if day.finished_at.present? %></td>
          <% else %>
            <td><%= day.after_finished_at.hour %></td>
            <td><%= set_minutes(day.after_finished_at) %></td>
          <% end %>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? && day.after_started_at.nil? && day.after_finished_at.nil? %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes), day.spread_day) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% elsif day.after_started_at.present? && day.after_finished_at.present? %>
              <%= str_times = working_times(day.after_started_at.floor_to(15.minutes), day.after_finished_at.floor_to(15.minutes), day.spread_day) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= day.estimated_finished_time.hour if day.estimated_finished_time.present? %></td>
          <td><%= set_minutes(day.estimated_finished_time) if day.estimated_finished_time.present? %></td>
          <td>
            <% if ((day.started_at.present? && day.finished_at.present?) || (day.after_started_at.present? && day.after_finished_at.present?)) && day.estimated_finished_time.present? %>
              <%= oneday_overtime = overtime_calculation(day.estimated_finished_time, day.overtime_spread_day, @user.designated_work_end_time) %>
              <% @oneday_overtime = oneday_overtime %>
              <% @total_overtime_times= @total_overtime_times.to_f + oneday_overtime.to_f %>
            <% end %>
          </td>
          <td><%= day.job_description %></td>
          <td><%= User.find(day.edit_attendance_boss).name + "　勤怠編集" + day.edit_attendance_request_status if day.edit_attendance_boss.present? && day.edit_attendance_request_status != "なし" %><br>
              <%= User.find(day.overtime_boss).name + "　残業" + day.overtime_request_status if day.overtime_boss.present? && day.overtime_request_status != "なし" %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <th rowspan="3"></th>
        <th colspan="2">累計日数</th>
        <th colspan="6">総合勤務時間</th>
        <th>累計在社時間</th>
        <th colspan="3"></th>
        <th>累計残業時間</th>
        <th></th>
        <th>所属長承認 
          <% if @one_month_attendance.one_month_request_status != "なし" && @one_month_attendance.one_month_boss.present? %>
            <%= User.find(@one_month_attendance.one_month_boss).name + " " + @one_month_attendance.one_month_request_status  %>
          <% else %>
            &nbsp;&nbsp;未
          <% end %>
        </th>
      </tr>
      
      <tr>
        <td rowspan="2" colspan="2"><%= @attendances.count %></td>
        <td rowspan="2" colspan="6"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td>
        <td rowspan="2"><%= format("%.2f", @total_working_times.to_f) %></td>
        <td rowspan="2" colspan="3"></td>
        <td rowspan="2"><%= format("%.2f", @total_overtime_times.to_f) %></td>
        <td rowspan="2"></td>
        
        <% if current_user == @user %>
          <td>
            <%= form_with(model: @user, url: applies_request_one_month_user_path(date: @first_day), method: :patch, local: true) do |f|  %>
              <%= f.fields_for "applies[]", @one_month_attendance do |apply| %>
                <%= apply.hidden_field :one_month_request_status, value: "申請中" %>
                <%= apply.collection_select :one_month_boss, @superiors, :id, :name, {:include_blank => "選択してください。", selected: "選択してください。"}, {class: "form-control"} %>
              <% end %>
        
              <% if @one_month_attendance.one_month_request_status == "否認" || @one_month_attendance.one_month_request_status == "承認" %>
                <%= f.submit "再申請", data: { confirm: "再申請してよろしいですか？" }, class: "btn btn-default btn-primary btn-request form-control" %>
              <% elsif @one_month_attendance.one_month_request_status == "申請中" %>
                <%= f.submit "申請先変更", data: { confirm: "申請先変更してよろしいですか？" }, class: "btn btn-default btn-primary btn-request form-control" %>
              <% else %>
                <%= f.submit "申請", data: { confirm: "申請してよろしいですか？" }, class: "btn btn-default btn-primary btn-request form-control" %>
            <% end %>
          <% end %>
          </td>
        </tr>  
        <% elsif @one_month_attendance.one_month_boss.present? %>
      <tr>
        <td>所属長承認 <%= User.find(@one_month_attendance.one_month_boss).name + " " + @one_month_attendance.one_month_request_status %></td>
      </tr>
      <% else %>
      <tr>
        <td>所属長承認 未</td>
      </tr>    
        <% end %>
    </tfoot>
  </table>
  
  <% unless current_user == @user %>
    <div class="footer-button">
      <%= link_to "戻る", user_path(current_user), class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>
</div>


<!-- モーダルウィンドウ表示 -->
<% if current_user == @user %>
  <div id="receive-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id="request-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id="receive-change-attendance" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
  <div id="receive-one-month-request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<% end %>

app/views/users/working_employee.html.erb
<% provide(:title, "出勤中社員一覧") %>
<% provide(:class_text, "working_employee") %>
<h1>出勤中社員一覧</h1>

<div class="container">
  <table class="table table-bordered table-condensed table-hover table-striped" id="table-working_employees">
    <% if @working_users.nil? %>
      <h1>現在出勤中の社員はいません。</h1>
    <% else %>
      <thead>
        <tr>
         <th>社員番号</th>
         <th>名前</th>
        </tr>
      </thead>
      <tbody>
        <% @working_users.each do |user| %>
          <% user.attendances.each do |attendance| %>
             <% if (Date.current == attendance.worked_on) && attendance.started_at != nil && attendance.finished_at == nil %>
          <tr>
            <td><%= user.employee_number %></td>
            <td><%= user.name %></td>
          </tr>
            <% end %>
          <% end %>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>