config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 拠点情報
  resources :bases, except: [:show, :new]
  
  resources :users do
    collection { post :import }
    get 'import'
    member do
      get 'export'
      get 'search'
      get 'working_employee'
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_user_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'attendances/request_overtime'
      patch 'attendances/update_overtime'
      get 'attendances/receive_overtime'
      patch 'attendances/decision_overtime'
      get 'attendances/edit_log'
      get 'attendances/receive_change_attendance'
      patch 'attendances/update_change_attendance'
      patch 'applies/request_one_month'
      get 'applies/receive_one_month_request'
      patch 'applies/decision_one_month_request'
      
    end
    resources :attendances, only: :update
  end
end
  

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validates :worked_on, presence: true
  validates :note, length: { maximum: 100 }, presence: true, allow_nil: true
  validates :estimated_finished_time, presence: true, allow_nil: true
  validates :job_description, presence: true, allow_nil: true
  validates :overtime_boss, presence: true, allow_nil: true
  validates :edit_attendance_boss, presence: true, allow_nil: true
  
  # 残業の承認・否認のステータス
  enum overtime_request_status: { なし: 0, 申請中: 1, 承認: 2, 否認: 3 }, _prefix: true
  
  # 勤怠編集の承認・否認のステータス
  enum edit_attendance_request_status: { なし: 0, 申請中: 1, 承認: 2, 否認: 3 }, _prefix: true
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  
  # 今日以外の日付で退勤時間が存在しない場合、出勤時間は無効
  validate :started_at_is_invalid_without_a_finished_at
  validate :before_started_at_is_invalid_without_a_before_finished_at
  validate :after_started_at_is_invalid_without_a_after_finished_at
  
  # 出勤・退勤時間どちらも存在する場合、出勤時間よりも退勤時間が早い場合は無効
  validate :started_at_than_finished_at_fast_if_invalid
  validate :after_started_at_than_after_finished_at_fast_if_invalid
  
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if (started_at.blank? && finished_at.present?)  || (before_started_at.blank? && before_finished_at.present?) || (after_started_at.blank? && after_finished_at.present?)
  end
  
  def started_at_is_invalid_without_a_finished_at
    if worked_on < Date.current
      unless (started_at.present? && finished_at.present?) || (started_at.blank? && finished_at.blank?)
        errors.add(:finished_at, "が必要です")
      end
    end
  end
  
  def before_started_at_is_invalid_without_a_before_finished_at
    if worked_on < Date.current
      unless (before_started_at.present? && before_finished_at.present?) || (before_started_at.blank? && before_finished_at.blank?)
        errors.add(:before_finished_at, "が必要です")
      end
    end
  end
  
  def after_started_at_is_invalid_without_a_after_finished_at
    if worked_on < Date.current
      unless (after_started_at.present? && after_finished_at.present?) || (after_started_at.blank? && after_finished_at.blank?)
        errors.add(:after_finished_at, "が必要です")
      end
    end
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if after_started_at.blank?
      if started_at.present? && finished_at.present? && !spread_day
        errors.add(:started_at, "より早い退勤時間は無効です。") if started_at > finished_at
      end
    end
  end
  
  def after_started_at_than_after_finished_at_fast_if_invalid
    if after_started_at.present? && after_finished_at.present? && !spread_day
      errors.add(:after_started_at, "より早い退勤時間は無効です。") if after_started_at > after_finished_at
    end
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :request_overtime, :update_overtime, :receive_overtime, :receive_change_attendance, :request_one_month,
                                  :update_change_attendance, :receive_one_month_request, :edit_log]
  before_action :logged_in_user, only: [:update, :edit_one_month, :request_overtime, :update_overtime, :receive_change_attendance, :update_change_attendance]
  before_action :correct_user, only: [:edit_one_month, :request_overtime, :update_overtime, :receive_overtime, :receive_change_attendance]
  before_action :superior_user, only: [:receive_change_attendance, :update_change_attendance, :receive_overtime, :decision_overtime]
  before_action :not_admin_user
  before_action :set_one_month, only: [:edit_one_month, :update_one_month, :request_overtime, :edit_log]
  before_action :select_superiors, only: [:edit_one_month, :update_one_month, :request_overtime, :update_overtime]
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  NO_CHECK_ERROR_MSG = "変更にチェックがないものは更新できません。"
  INVALID_ERROR_MSG = "無効な入力があった為、更新をキャンセルしました。"

  # 出退勤ボタンの勤怠登録
  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  # 勤怠修正ページへ
  def edit_one_month
  end
  
  # 社員による勤怠情報修正
  def update_one_month
    ActiveRecord::Base.transaction do
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        if (item)[:after_started_at].present? && (item)[:after_finished_at].present?
          if (item)[:edit_attendance_boss].present? && (item)[:note].present?
            attendance.edit_attendance_request_status = "申請中" 
            attendance.update_attributes!(item)
          else 
            flash[:danger] = "申請箇所には出社、退社、備考、指示者確認㊞が必要です。"
          end
        end
      end
    end
    flash[:success] = "1ヶ月分の勤怠情報を更新・申請しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = INVALID_ERROR_MSG
    redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  # 勤怠修正を受領
  def receive_change_attendance
    @change_attendance_requests = Attendance.order(:worked_on).where(edit_attendance_boss: @user.id, edit_attendance_request_status: "申請中").group_by(&:user_id)
  end
  
  # 上長による勤怠修正を承認・否認
  def update_change_attendance
    ActiveRecord::Base.transaction do
      change_attendance_params.each do |id, item|
        change_attendance = Attendance.find(id)
        if params[:user][:attendances][id][:change] == "true"
          if change_attendance.started_at.nil? || change_attendance.finished_at.nil?
            change_attendance.started_at = change_attendance.after_started_at
            change_attendance.finished_at = change_attendance.after_finished_at
          end
          change_attendance.update_attributes!(item)
        else
          flash[:danger] = NO_CHECK_ERROR_MSG
        end
      end
    end
    flash[:success] = "勤怠変更の決裁を更新しました。"
    redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid
     flash[:danger] = INVALID_ERROR_MSG
    redirect_to user_url(date: params[:date])
  end
  
  # 残業申請
  def request_overtime
    @attendance = Attendance.find_by(worked_on: params[:date])
    @attendances = @user.attendances.where(worked_on: @attendance.worked_on)
  end
  
  # 残業申請を受領
  def receive_overtime
    @overtime_requests = Attendance.order(:worked_on).where(overtime_boss: @user.id, overtime_request_status: "申請中").group_by(&:user_id)
  end
  
  # 社員が残業申請を登録 
  def update_overtime
    @user = User.find(params[:id])
    ActiveRecord::Base.transaction do
      overtime_info_params.each do |id, item|
        if params[:user][:attendances][id][:overtime_boss].present? && params[:user][:attendances][id][:job_description].present? 
          @overtime = Attendance.find(id)
          @overtime.update_attributes!(item)
        else
          flash[:danger] = "終了予定時間、業務内容、指示者確認㊞は必須です。"
          redirect_back(fallback_location: root_path) and return
        end
      end
    end
    @superior = User.find(@overtime.overtime_boss)
    flash[:success] = "#{@superior.name}に残業申請をしました。"
    redirect_back(fallback_location: root_path)
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = INVALID_ERROR_MSG
    redirect_to user_url(date: params[:date])
  end
  
  # 上長の残業申請の承認・否認
  def decision_overtime
    ActiveRecord::Base.transaction do
      decision_overtime_params.each do |id, item|
        decision_overtime = Attendance.find(id)
        if params[:user][:attendances][id][:change] == "true"
          decision_overtime.update_attributes!(item)
        else
          flash[:danger] = NO_CHECK_ERROR_MSG
        end
      end
    end
    flash[:success] = "残業申請の決裁を更新しました。"
    redirect_to user_url(current_user, date: params[:date])
  rescue ActiveRecord::RecordInvalid
    flash[:danger] = INVALID_ERROR_MSG
    redirect_to user_url(current_user, date: params[:date])
  end
  
  # 勤怠ログ
  def edit_log
    if params[:worked_on].present?
      first_day = DateTime.parse(params[:worked_on] + "-" + "01") # 文字列で取得した日付に文字列の01を加えてdatetime型に型変換し月初日をセット
      last_day = first_day.end_of_month # 月末日を取得
      # Attendanceテーブルからworked_onの日付順で整列し、現在ログインしているユーザ、承認のものを取得し、paramsで取得した月に合致するものをセット
      @approval_change_attendance_requests = Attendance.order(:worked_on).where(user_id: current_user, edit_attendance_request_status: "承認").where(worked_on: first_day..last_day) 
      if @approval_change_attendance_requests.size > 0
        render
      else
        flash.now[:danger] = "選択月の勤怠編集ログはありません。"
      end
    end
  end
  
  private
  
    # 1ヶ月分の勤怠情報を扱う
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :finished_at, :before_started_at, :before_finished_at, :after_started_at, :after_finished_at, :edit_attendance_boss, :note, :spread_day])[:attendances]
    end
    
    # 勤怠情報修正承認・否認時のストロングパラメータ
    def change_attendance_params
      params.require(:user).permit(attendances: [:edit_attendance_request_status])[:attendances]
    end
    
    # 残業申請時のストロングパラメータ
    def overtime_info_params
      params.require(:user).permit(attendances: [:estimated_finished_time, :overtime_spread_day, :overtime_boss, :job_description, :overtime_request_status])[:attendances]
    end
    
    # 残業承認・否認時のストロングパラメータ
    def decision_overtime_params
      params.require(:user).permit(attendances: [:overtime_request_status])[:attendances]
    end
    
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価
    if Date.current == attendance.worked_on
      return "出社" if attendance.started_at.nil?
      return "退社" if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかったらfalseを返す
    false
  end
  
   # 出勤時間と退勤時間を受け取り、在社時間を計算して返す
  def working_times(started_at, finished_at, spread_day)
    @attendance = Attendance.find(params[:id])
    @attendance.spread_day = spread_day
    if @attendance.spread_day
      format("%.2f",(((finished_at - started_at) / 60) / 60.0) + 24)  # 日跨ぎ勤務
    else
      format("%.2f",(((finished_at - started_at) / 60) / 60.0)) # 日跨ぎ無しで勤務
    end
  end
  
  # 時間を15分刻みで表示
  def set_minutes(time)
    format("%.2d", time.floor_to(15.minutes).min)
  end
  
  # 残業時間を計算
  def overtime_calculation(estimated_finished_time, overtime_spread_day, designated_work_end_time)
    @attendance = Attendance.find(params[:id])
    @attendance.overtime_spread_day = overtime_spread_day
    estimated_finished_time = estimated_finished_time.round_to(15.minutes)
    estimated_finished_time = estimated_finished_time.change(year: Date.current.year, month: Date.current.month, day: Date.current.day)
    designated_work_end_time = designated_work_end_time.change(year: Date.current.year, month: Date.current.month, day: Date.current.day)
    if @attendance.overtime_spread_day == true
      format("%.2f",(((estimated_finished_time.time - designated_work_end_time.time) / 60) / 60.0) + 24)
    elsif (estimated_finished_time - designated_work_end_time) <= 0
      flash.now[:danger] = "残業時間としてカウントできない値が入っています。"
      return -1.00
    else
      format("%.2f",(((estimated_finished_time.time - designated_work_end_time.time) / 60) / 60.0))
    end
  end
  
end

app/views/attendances/_edit_log.html.erb
<% @approval_change_attendance_requests.each do |day| %>
  <tr>
    <td><%= l(day.worked_on, format: :default) %></td>
    <td><%= l(day.before_started_at, format: :time) if day.before_started_at.present? %></td>
    <td><%= l(day.before_finished_at, format: :time) if day.before_finished_at.present? %></td>
    <td><%= l(day.after_started_at, format: :time) if day.after_started_at.present? %></td>
    <td><%= l(day.after_finished_at, format: :time) if day.after_finished_at.present? %></td>
    <td><%= User.find(day.edit_attendance_boss).name %></td>
    <td><%= day.updated_at.in_time_zone('Tokyo').strftime("%Y/%m/%d") %></td>
  </tr>
<% end %>

app/views/attendances/_receive_change_attendance.html.erb
<% provide(:class_text, 'receive_change_attendance') %>
<% provide(:button_text, '変更を送信する') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: attendances_update_change_attendance_user_path, local: true, method: :patch) do |f| %>
        <% @change_attendance_requests.each do |key, change_attendance_request| %>
          <table class="table table-bordered request-modal">
                
            <thead>
              <tr>
                <% @member = User.find(key) %>
                <h1 class="modal-title"><%= User.find(key).name %>からの勤怠変更申請</h1>
                <th rowspan="3">日付</th>
                <th rowspan="3">曜日</th>
                <th colspan="4">変更前</th>
                <th colspan="4">変更後</th>
                <th rowspan="3">備考</th>
                <th rowspan="3">指示者確認㊞</th>
                <th rowspan="3">変更</th>
                <th rowspan="3">勤怠を確認する</th>
              </tr>
              <tr>
                <th colspan="2">出社</th>
                <th colspan="2">退社</th>
                <th colspan="2">出社</th>
                <th colspan="2">退社</th>
              </tr>
              <tr>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
                <th>時</th>
                <th>分</th>
              </tr>
            </thead>
                    
            <tbody>
              <% change_attendance_request.each do |day| %>
                <%
                  day_of_week_color = case $days_of_the_week[day.worked_on.wday]
                    when "土"
                      "text-primary"
                    when "日"
                      "text-danger"
                    end
                %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                <tr>
                  <td><%= l(day.worked_on, format: :short) %></td>
                  <td class="<%= day_of_week_color %>"><%= $days_of_the_week[day.worked_on.wday]%></td>
                  <td><%= day.started_at.hour if day.started_at.present? %></td>
                  <td><%= set_minutes(day.started_at) if day.started_at.present? %></td>
                  <td><%= day.finished_at.hour if day.started_at.present? %></td>
                  <td><%= set_minutes(day.finished_at) if day.finished_at? %></td>
                  <td><%= day.after_started_at.hour if day.after_started_at.present? %></td>
                  <td><%= set_minutes(day.after_started_at) if day.after_started_at.present? %></td>
                  <td><%= day.after_finished_at.hour if day.after_finished_at.present? %></td>
                  <td><%= set_minutes(day.after_finished_at) if day.after_finished_at.present? %></td>
                  <td><%= day.note %></td>
                  <td><%= attendance.select :edit_attendance_request_status, Attendance.edit_attendance_request_statuses.keys.to_a, {}, class: "form-control" %></td>
                  <td><%= attendance.check_box :change, { class: "check_box" }, true, false %></td>
                  <td><%= link_to "確認",user_path(id: @member, date: day.worked_on.beginning_of_month), class: "btn btn-primary btn-#{yield(:class_text)}" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
       <% end %>
          
      <table>
        <div class="footer-button">
          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
            <button type="button" class="btn btn-primary btn-<%= yield(:class_text) %>" data-dismiss="modal">
              戻る
            </button>
        </div>
      </table>
    <% end %>
  </div>
</div>

app/views/attendances/_receive_change_attendance_request.html.erb
<% provide(:class_text, 'receive_change_attendance_request') %>
<% provide(:button_text, '変更を送信する') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: attendances_receive_one_month_request_user_path, local: true, method: :patch) do |f| %>
        <% @one_month_requests.each do |key, overtime_requests| %>
          <table class="table table-bordered">
                
            <thead>
              <tr>
                <% @member = User.find(key) %>
                <h1 class="modal-title"><%= User.find(key).name %>からの残業申請</h1>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定勤務終了時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
                    
            <tbody>
              <% overtime_requests.each do |day| %>
                <%
                  day_of_week_color = case $days_of_the_week[day.worked_on.wday]
                    when "土"
                      "text-primary"
                    when "日"
                      "text-danger"
                    end
                %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                <tr>
                  <td><%= l(day.worked_on, format: :short) %></td>
                  <td class="<%= day_of_week_color %>"><%= $days_of_the_week[day.worked_on.wday]%></td>
                  <td><%= day.estimated_finished_time.strftime("%H:%M") %></td>
                  <td><%= @member.designated_work_end_time.strftime("%H:%M") %></td>
                  <td><%= overtime_calculation(day.estimated_finished_time, day.spread_day, @member.designated_work_end_time) %></td>
                  <td><%= day.job_description %></td>
                  <td><%= attendance.select :overtime_request_status, Attendance.overtime_request_statuses.keys.to_a, {}, class: "form-control" %></td>
                  <td><%= attendance.check_box :change, { class: "check_box" }, true, false %></td>
                  <td><%= link_to "確認",user_path(id: @member, date: day.worked_on.beginning_of_month), class: "btn btn-primary btn-#{yield(:class_text)}" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
       <% end %>
          
      <table>
        <div class="footer-button">
          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
            <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
              キャンセル
            </button>
        </div>
      </table>
    <% end %>
  </div>
</div>

app/views/attendances/_receive_overtime.html.erb
<% provide(:class_text, 'receive_overtime') %>
<% provide(:button_text, '変更を送信する') %>


<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= form_with(model: @user, url: attendances_decision_overtime_user_path, local: true, method: :patch) do |f| %>
        <% @overtime_requests.each do |key, overtime_requests| %>
          <table class="table table-bordered request-modal">
                
            <thead>
              <tr>
                <% @member = User.find(key) %>
                <h1 class="modal-title"><%= User.find(key).name %>からの残業申請</h1>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>指定勤務終了時間</th>
                <th>時間外時間</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
                <th>変更</th>
                <th>勤怠を確認する</th>
              </tr>
            </thead>
                    
            <tbody>
              <% overtime_requests.each do |day| %>
                <%
                  day_of_week_color = case $days_of_the_week[day.worked_on.wday]
                    when "土"
                      "text-primary"
                    when "日"
                      "text-danger"
                    end
                %>
                <%= f.fields_for "attendances[]", day do |attendance| %>
                <tr>
                  <td><%= l(day.worked_on, format: :short) %></td>
                  <td class="<%= day_of_week_color %>"><%= $days_of_the_week[day.worked_on.wday]%></td>
                  <td><%= day.estimated_finished_time.strftime("%H:%M") %></td>
                  <td><%= @member.designated_work_end_time.strftime("%H:%M") %></td>
                  <td><%= overtime_calculation(day.estimated_finished_time, day.overtime_spread_day, @member.designated_work_end_time) %></td>
                  <td><%= day.job_description %></td>
                  <td><%= attendance.select :overtime_request_status, Attendance.overtime_request_statuses.keys.to_a, {}, class: "form-control" %></td>
                  <td><%= attendance.check_box :change, { class: "check_box" }, true, false %></td>
                  <td><%= link_to "確認",user_path(id: @member, date: day.worked_on.beginning_of_month), class: "btn btn-primary btn-#{yield(:class_text)}" %></td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
       <% end %>
          
      <table>
        <div class="footer-button">
          <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
            <button type="button" class="btn btn-primary btn-<%= yield(:class_text) %>" data-dismiss="modal">
              戻る
            </button>
        </div>
      </table>
    <% end %>
  </div>
</div>

app/views/attendances/edit_log.html.erb
<div class="container">
  <h1>勤怠ログ</h1>
  
  <div class="row form-group">
    <div class="col-md-2" id="search-attendance-log">
      <%= form_with model: @attendance, url: attendances_edit_log_user_path, id: "form_edit_log", method: :get, remote: true do |f|  %>
        <%= f.month_field(:worked_on, required: true, class: "form-control") %>
        <%= f.button "検索", id: "btn_edit_log", class: " btn-primary search-btn form-control" %>
      <% end %>
    </div>
    
    <script>
      $(function() {
        $('#btn_edit_log').click(function() {
          
        $('#form_edit_log').submit();
        })
      })
    </script>
    
    <div id ="edit_attendance_header">
      <table class="table table-bordered table-condensed table-hover" id="table-attendances-log">
        <thead>
          <tr>
            <th>日付</th>
            <th>変更前出社時間</th>
            <th>変更前退社時間</th>
            <th>変更後出社時間</th>
            <th>変更後退社時間</th>
            <th>指示者</th>
            <th>承認日</th>
          </tr>
        </thead>

      <div id="edit_attendance_log">
        <tbody>
          <% if @approval_change_attendance_requests.present? %>
            <%= render 'edit_log' %>
          <% end %>
        </tbody>
      </div>
    </table>
      
      
    <div class="center">
      <%= link_to "戻る", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
    </div>
  </div>
</div>

app/views/attendances/edit_log.js.erb
$('#edit-attendance-log').html('');
$('#edit-attendance-log').html('<%= j render partial: 'edit_log', collections: @approval_change_attendance_requests %>');

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%
            day_of_week_color = case $days_of_the_week[day.worked_on.wday]
            when "土"
              "text-primary"
            when "日"
              "text-danger"
            end
          %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td class="<%= day_of_week_color %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if Date.current < day.worked_on %>
                <td><%= attendance.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :after_started_at, class: "form-control" %></td>
                <td><%= attendance.time_field :after_finished_at, class: "form-control" %></td>
                <% if day.before_started_at.nil? && day.edit_attendance_request_status == "承認" %>
                  <%= attendance.hidden_field :before_started_at, value: day.started_at %>
                  <%= attendance.hidden_field :before_finished_at, value: day.finished_at %>
                <% end %>
                <%= attendance.hidden_field :started_at, value: day.after_started_at if day.edit_attendance_request_status == "承認" %>
                <%= attendance.hidden_field :finished_at, value: day.after_finished_at if day.edit_attendance_request_status == "承認" %>
              <% end %>
              <td><%= attendance.check_box :spread_day, :as => :boolean if Date.current >= day.worked_on %></td>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <%= working_times(day.started_at, day.finished_at, day.spread_day) %>
                <% elsif day.after_started_at.present? && day.after_finished_at.present? %>
                  <%= working_times(day.after_started_at, day.after_finished_at, day.spread_day) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, placeholder: "変更理由を入力してください。", class: "form-control" if Date.current >= day.worked_on %></td>
              <td><%= attendance.collection_select :edit_attendance_boss, @superiors, :id, :name, { :include_blank => "選択してください。", selected: "選択してください。" }, { class: "form-control" } if Date.current >= day.worked_on %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <div class="center">
    <%= f.submit "編集を保存", class: "btn btn-lg btn-primary" %>
    <%= link_to "戻る", user_path(date: @first_day), class: "btn btn-lg btn-primary" %>
  </div>
<% end %>